export const TODO_ADD = 'TODO_ADD'
export const TODO_REMOVE = 'TODO_REMOVE'
export const TODO_TOGGLE = 'TODO_TOGGLE'
export const TODOS_FILTER = 'TODOS_FILTER'
export const TODOS_REPLACE = 'TODOS_REPLACE'
